### ISSUE TITLE
Use a single certificate per HEI?

### ISSUE THREAD

**Issue by mikesteez** [erasmus-without-paper/ewp-specs-architecture#10]
There are two ways of designing the API, one is to have the HEI id as an explicit parameter in all requests and the other is to have it implicit through the unique client certificate per institution.

Example with implicit request:

`/umu/list-agreements`

This is where Umeå University (umu) is exposing the fictive list agreements API. This returns a list of agreements with the calling institution. 

Example with explicit HEI parameter
`/umu/list-agreements?calling_HEI=382`

This parameter has to be exposed in almost every API. The argument for this is to have a single client certificate for several institutions. I believe that this is worrysome for several reasons:
- If we introduce electronic signatures of the transported data, we would require one key per institution. http://www.symantec.com/connect/articles/digital-signatures-and-european-laws
- We mix authentication with business logic 
- (Emotional) It does not look good

On the positive side
- It might be easier to implement as you do not have to pass information regarding the calling institution trough a ThreadLocal or the UriInfo on the Java platform.

**Comment by mpuzar** [comment]
Signing data is outside of the scope of API design, and (if AdES or AdESQC is used) it would need separate keys anyway.

This (quite radical) change in the architecture would mean a much more complicated implementation of hosts who are in charge of multiple institutions, both with regards to contact points and number of certificates they would need to handle.

**Comment by wrygiel** [comment]
I think that I might agree with @mikesteez on this. If we are indeed deciding to go away from the multi-HEI architecture (and everyone seemed to vote for it - see https://github.com/erasmus-without-paper/ewp-specs-api-echo/issues/3 for details), then I feel that each HEI should by uniquely identifiable by an unique client certificate.

**Comment by mkurzydlowski** [comment]
I also feel that each HEI should use its own certificate and using them for identifying the caller seems like an elegant solution. I hope that those certificates could also be used for data/document signing.

**Comment by mpuzar** [comment]
In fact, in our case we will probably be signing documents with one single certificate as well, covering all the institutions.

**Comment by wrygiel** [comment]
We have decided to stay with A1 architecture in https://github.com/erasmus-without-paper/ewp-specs-api-echo/issues/3, so this thread can be closed now.
