### ISSUE TITLE
Restrict values for our xml:lang attributes

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#11]
I have just noticed one minor issue which we should address.

The `xml:lang` attributes which we have used in our [StringWithOptionalLang](https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/v1.2.3/common-types.xsd#L30) and [MultilineStringWithOptionalLang](https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/v1.2.3/common-types.xsd#L62) data types have "a flaw" of a sort. (Or perhaps it's a feature?)

I was just implementing an update to ewp-registry-client, and have followed the [XML namespace specs](https://www.w3.org/2001/03/xml.xsd) through [xs:language specs](https://www.w3.org/TR/xmlschema11-2/#language) to [RFC 3066](https://www.ietf.org/rfc/rfc3066.txt) where I found out that **`xml:lang` accepts both 2 and 3-letter language codes.**

This might be a problem, because - if we allow that - then all programmers will need to remember to search for their languages using both versions of the key (e.g. `eng` and `en`, instead of only `en`).

I propose to change our specs and require everyone to use 2-letter codes only (the ISO 839-1 subset of all valid `xml:lang` attributes). This would be documented in our `common-types.xsd` file.

**Comment by wrygiel** [comment]
BTW, it's not only about 3-letter codes. `xml:lang` accepts many other language options too. This is the regexp used there:

```
[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*
```

**Comment by wrygiel** [comment]
**Solution 1.** As described above. Keep using `xml:lang` attributes, but remind everyone to restrict their values to ISO 839-1.

Other options:

**Solution 2.** Deprecate `xml:lang` attributes in our schemas entirely, and use an equivalent of our own.

**Solution 3.** Don't change anything. Keep `xml:lang` and respect all the values it might have. This might make it harder for clients to find proper languages in various cases, but it also allows EWP to support _variations_ of languages (e.g. American English vs British English). For example, just a minute ago I have noticed that @kaiqu has used `xml:lang="en-us"` in one of his examples - perhaps it would be useful to keep such distinction?

**Comment by mikesteez** [comment]
As W3C refers to http://www.rfc-editor.org/rfc/bcp/bcp47.txt when discussing `xml:lang`
In the text, they say "shortest ISO 639 code" and "sometimes followed by extended language subtags". I suggest we go with solution 1 with the addition that clients MAY interpret the extended language subtag, if they have the possibility to do so.

**Comment by georgschermann** [comment]
I'd suggest to stick to the ISO 639-1 codes which should be sufficient inside our use cases and the EU. (http://publications.europa.eu/code/en/en-5000800.htm)

**Comment by wrygiel** [comment]
> I'd suggest to stick to the ISO 639-1 codes which should be sufficient inside our use cases and the EU. 

Would you prefer solution 1 or 2? Both of them encourage you to use 2-letter codes, but solution 2 is more restrictive (it enforces it on the XML Schema level).

**Comment by georgschermann** [comment]
solution 1 should be enough I think

**Comment by wrygiel** [comment]
During discussion in Warsaw it turned out that might need these "extra features" (among other things, to be able to specify that particular value has been transliterated). I didn't understand why we need it exactly, but perhaps it doesn't matter.

In conclusion, we want to be able to use the full potential of `xs:language` (if not now, then perhaps in the future). This means, that we should not attempt restrict the server developers, but to instruct client developers instead.

**Comment by mikesteez** [comment]
@wrygiel could you elaborate on this? What are the implications for server- and client-developers?

**Comment by wrygiel** [comment]
Server developers will be allowed to use extensions, as `xml:lang` specification allows it. Client developers will be required to expect that `xml:lang` may include extensions. They may need to truncate these extensions before comparing or storing the values.

**Comment by wrygiel** [comment]
> I didn't understand why we need it exactly

I will try to understand this topic exactly before I update the specification. I suspect that we might have misunderstood each other in this aspect.

Regardless, I think that the clients should expect that `xml:lang` MAY sometimes contain extensions. These extensions might be useful in some scenarios (e.g. `en-US` vs `en-GB`). It's up to the server and the clients to decide if they want to use them, but the network should not deny them to be used. What do you think?

**Comment by mikesteez** [comment]
@wrygiel yes I agree with the last comment!

**Comment by georgschermann** [comment]
+1 for 2-letter codes with optional extension
