### ISSUE TITLE
Decide on the format of postal addresses

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#13]
We should decide on the XML Schema for addresses - both physical ones and postal ones.

We need a list of solutions to pick from. Everyone is welcome to submit their proposals. **Let's assign numbers to each proposal for easy referral.**

@erasmus-without-paper/all-members

**Comment by wrygiel** [comment]
### Solution 1: A string

(I no longer think it's a good idea.) **Make it a string.** Horribly simple, and not so bad as you'd think.

**Pros:**
- **Easy for server developers.** The greatest advantage is that every server will be able to provide this format with ease, regardless of the format kept in their database. None of the other data formats will give us this advantage.
- **Easy to display properly for the client.** In this solution, it is the _server_ who decides _how the address should be displayed_, where the line breaks and postal codes are, etc. As these rules usually differ from country to country, this will often give us **the best user experience**.
- If there's a need of parsing those (is there? in our use cases?), then there are lots of _free_ online geocoding and reverse geocoding APIs out there. And this means that _it probably doesn't take much to take such string and convert it to any format the client desires_.
- Even if we don't make it the primary format, it still seems to be a **good secondary "fallback" format.** That is, we should consider allowing the servers to give us the addresses in this format if they cannot provide the address in the "primary" format (regardless of what primary format we choose).

**Cons:**
- One **big** disadvantage here: Some partners might be required to store addresses in a structured format (even though there seems to be no use case forcing us to do that). This will require client developers to use external geocoding libraries. **And I could be wrong about the ease of use of those!** (I haven't tried them much.)

**Comment by wrygiel** [comment]
### Solution 2

Janina proposes to base the format on the one used in the Mobility project (not to be confused with the Mobility Tool):

![image](https://cloud.githubusercontent.com/assets/2168535/19416487/4fe0a698-9392-11e6-91a6-655c5771047f.png)

``` xml
<xsd:complexType name="addressT" >
  <xsd:sequence>
    <xsd:element name="street" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>The 'street' ('streetAddress' in X.500) attribute type contains site information from a postal address (i.e., the street name, place, avenue, and the house number).&quot;</xsd:documentation>
      </xsd:annotation>
    </xsd:element>
    <xsd:element name="postalCode" type="xsd:string"/>
    <xsd:element name="localityName" type="xsd:string">
      <xsd:annotation>
        <xsd:documentation>The 'localityName' ('localityName' in X.500) attribute type contains names of a locality or place, such as a city, county, or other geographic region.</xsd:documentation>
      </xsd:annotation>
    </xsd:element>
    <xsd:element name="countryName" type="tns:countryCodeT"/>
    <xsd:element minOccurs="0" name="stateOrProvinceName" type="xsd:string"/>
  </xsd:sequence>
</xsd:complexType>
```

**Comment by wrygiel** [comment]
@kaiqu, Luis, could you include your proposals here?

**Comment by kaiqu** [comment]
### Solution 3

I proposed the standard defined here (minus the person info):
http://xml.coverpages.org/HR-XML-PostalAddress-1_2.pdf
Mainly because it contains a **type** distinguishing between street (visiting) and post office box (mailing) addresses. Since the workshop concluded that addresses won't be algorithmically processed, there is no need for such a type, so I'm happy to withdraw the suggestion.

Of the previous alternatives, I would prefer solution 2: Without any structure, it would be hard for clients to store/display the addresses properly (if geocoding libs don't solve the problem easily, as Wojtek suggests). Also, the reuse of a previous Mobility standard appeals to me. But I also see the merits of solution 1, so haven't got strong opinions about this.

**Comment by vgiralt** [comment]
I agree with going with and established standard, any standard, being it the one used in solution 2 based on the Mobility project, or the address attributes in LDAP, and align with solution 1 for filling the postalAddress attribute in the most common way: substituting newlines for $ so it can be stored in one line and displayed in several lines. Like:
Blvd. Louis Pasteur, 33 $ Servicio Central de Informática $ Universidad de Málaga $ 29071 Málaga $  $ Spain
that will display like this:
Blvd. Louis Pasteur, 33
Servicio Central de Informática
Universidad de Málaga
29071 Málaga

Spain

**Comment by wrygiel** [comment]
### Solution 4

I did some more research. I analyzed the SQL structures of some public databases. It seems that all of them settled on using a single common format. It's quite similar to the format proposed in Solution 2, but a bit more flexible, with 3-4 address lines instead of a single street element (which can be easily combined into a single line, if need be).

I have built this schema based on all I found (it's just a first version, but the elements won't change, I think):

``` xml
<xs:element name="addressLine" minOccurs="0" maxOccurs="4" type="xs:string">
  <xs:annotation>
    <xs:documentation>
      There are many valid options here. These fields (there can be as much as 4 of
      them) may contain street name, building number, the name of the addressed
      entity (e.g. the name of the faculty, or a person), a post-office box number,
      etc.

      Server developers SHOULD attempt to provide this data in a form of multiple
      &lt;addressLine&gt; elements, but they are also allowed to have it all in a
      single line (e.g. comma-separated).

      Client developers MAY combine the lines with commas, if their databases do not
      allow them to hold 4 address lines.
    </xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="locality" minOccurs="0" type="xs:string">
  <xs:annotation>
    <xs:documentation>
      The name of the settlement (city/town/village). Both postal and map localities
      are allowed.

      If this address is supposed to be postal address, then it is recommended to use
      a postal locality here (postal authority often situated in a nearby large town).
      Note however, that a map locality is also acceptable, as the postal code will
      usually resolve any problems here, to allow correct delivery even if the
      official post-locality is not used.
    </xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="region" minOccurs="0" type="xs:string">
  <xs:annotation>
    <xs:documentation>
      An optional name of the region (many countries don't use them). Any kind of
      administrative division such as state, province, voivodeship, etc.
    </xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="postalCode" minOccurs="0" type="xs:string">
  <xs:annotation>
    <xs:documentation>
      The postal code. This is often (but not always) required if the address is
      supposed to be the postal address. It may include dashes and other formatting
      characters. Note, that in some countries it can be as long as 10 characters.
    </xs:documentation>
  </xs:annotation>
</xs:element>
<xs:element name="country" minOccurs="0" type="CountryIsoCode">
  <xs:annotation>
    <xs:documentation>
      ISO 3166-1 alpha-2 country code.
    </xs:documentation>
  </xs:annotation>
</xs:element>
```

#### Examples

``` xml
<example1>
  <addressLine>Janina Mincer-Daszkiewicz</addressLine>
  <addressLine>Faculty of Mathematics, Informatics and Mechanics</addressLine>
  <addressLine>Banacha 2</addressLine>
  <locality>Warszawa</locality>
  <postalCode>02-097</postalCode>
  <country>PL</country>
</example1>

<example2>
  <addressLine>PO Box 42475</addressLine>
  <locality>Houston</locality>
  <region>Texas</region>
  <postalCode>TX 77002</postalCode>
  <country>US</country>
</example2>
```

**Comment by wrygiel** [comment]
Which of the elements should be required? My guess is:
- At least one `<addressLine>`
- `<locality>`
- `<country>`

It seems that postal codes should not be required, as some countries do not use them.

**Comment by kaiqu** [comment]
I vote for solution 4 with the suggested required elements.

**Comment by wrygiel** [comment]
Quick analysis of ~~solution 2~~ solution 3: That's a good suggestion too! They use proper semantic versioning, and their specifications have XML Schemas attached (though without any XML namespaces, for some reason). This organization releases open standards for handling _human resources_ in general.

**Comment by wrygiel** [comment]
Sorry, I meant solution 3 in the previous comment.

**Comment by wrygiel** [comment]
However, solution 3 is also more complex than other solutions. For example, if we'd like to use it without changing it, then we would also be required to use its dependcies, such as the [`PersonName` element](http://xml.coverpages.org/HR-XML-PersonName-1_2.pdf).

We could also use a subset of the standard, in an XML namespace of our own - that would make it easier.

We will think more on all of these options. (I you have any more of them, then it's still okay to submit them.)

**Comment by georgschermann** [comment]
I'd suggest to not stick with postal/visiting adress, but instead allow unlimited different adresses (postal, visiting, international office, studentpoint, main campus, library, ...) with a type or description.

For the adress itself id suggest solution 4

**Comment by wrygiel** [comment]
@georgschermann, I think you misunderstood Kai's intention. Each of these entities (library, main campus) may have both "street address" (aka visiting address) and "mailing address" (aka postal address). In many scenarios, this distinction seems important: http://painintheenglish.com/case/3604

**Comment by georgschermann** [comment]
ok I see,
in our system we use one address for both purposes with an optional PO address line.
I don't know if a case exists where the postal address would be on a different zip code or city than the street address

**Comment by kaiqu** [comment]
> I don't know if a case exists where the postal address would be on a different zip code or city than the street address

There are cases in Norway where at least the zip code is different.

**Comment by georgschermann** [comment]
then these 2 types of address would be separately needed per "location entitiy"

**Comment by janinamincer-daszkiewicz** [comment]
I like option 3 in its original form. Also like PersonName coming from the same standard (http://xml.coverpages.org/HR-XML-PersonName-1_2.pdf). Let's folow those, some people have already spend a lot of time on them. May be we might find more useful standards there in http://xml.coverpages.org/index.html.

**Comment by wrygiel** [comment]
I will look into option 3 more then. I will verify it satisfies all our use cases and doesn't introduce problems of its own. I will post results here.

**Comment by wrygiel** [comment]
I have registered on http://www.hropenstandards.org/ site. Turns out version 1.2 of their standards is quite obsolete. I was able to acquire version 3.1 from their site. The base structure of the `Address` element looks like this:

``` xml
<xsd:complexType name="AddressType">
  <xsd:complexContent>
    <xsd:extension base="AddressBaseType">
      <xsd:sequence>
        <xsd:element ref="UserArea" minOccurs="0"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="EffectiveDateAttributeGroup"/>
      <xsd:attribute name="currentAddressIndicator" type="oa:IndicatorType"/>
    </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="AddressBaseType" abstract="true">
  <xsd:annotation>
    <xsd:documentation source="http://www.openapplications.org/oagis/9">
      Address BaseType provides the information about the address or semantic address
      of an associated entity.<ccts:DefinitionText>Based on OAGIS AddressBaseType.
      Exception:CountryCode uses the HR country code list.</ccts:DefinitionText>

      <ccts:UsageRule>
        Example values are:

        "Residence Address"   Residence Address is a primary, legal address that is
          related to a party.  For a person, the Home Residence Address is used by an
          employer for payroll, taxation, and benefit program eligibility.

        "Postal Address"   Set of precise and complete information on the basis of
          which an item can be forwarded and delivered to an addressee.  An address
          will be considered a postal address only if it is explicitly collected as
          such.

        "Delivery Address"   Delivery Address is an address which is to be used to
          physically deliver the related object.

        "Bill To"  An address to which invoices are sent.

        "Accounts Recievable"   An address to which payments are set.
      </ccts:UsageRule>
    </xsd:documentation>
  </xsd:annotation>
  <xsd:sequence>
    <xsd:element ref="ID" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="oa:FormatCode" minOccurs="0"/>
    <xsd:element ref="oa:AttentionOfName" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="oa:CareOfName" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:choice>
      <xsd:element ref="oa:AddressLine" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:sequence>
        <xsd:element ref="oa:LineOne" minOccurs="0"/>
        <xsd:element ref="oa:LineTwo" minOccurs="0"/>
        <xsd:element ref="oa:LineThree" minOccurs="0"/>
        <xsd:element ref="oa:LineFour" minOccurs="0"/>
        <xsd:element ref="oa:LineFive" minOccurs="0"/>
      </xsd:sequence>
      <xsd:sequence>
        <xsd:element ref="oa:BuildingNumber" minOccurs="0"/>
        <xsd:element ref="oa:BuildingName" minOccurs="0"/>
        <xsd:element ref="oa:StreetName" minOccurs="0"/>
        <xsd:element ref="oa:Unit" minOccurs="0"/>
        <xsd:element ref="oa:Floor" minOccurs="0"/>
        <xsd:element ref="oa:PostOfficeBox" minOccurs="0"/>
        <xsd:element ref="oa:DeliveryPointCode" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:choice>
    <xsd:element ref="oa:CitySubDivisionName" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="oa:CityName" minOccurs="0"/>
    <xsd:element ref="oa:CountrySubDivisionCode" minOccurs="0" maxOccurs="unbounded"/>
    <xsd:element ref="CountryCode" minOccurs="0"/>
    <xsd:element ref="oa:PostalCode" minOccurs="0"/>
    <xsd:element ref="oa:Status" minOccurs="0"/>
    <xsd:element ref="oa:Preference" minOccurs="0"/>
  </xsd:sequence>
  <xsd:attribute name="languageCode" type="LanguageCodeContentType" use="optional"/>
  <xsd:attribute name="type" type="oa:NormalizedStringType"/>
</xsd:complexType>

<!-- Skipped: EffectiveDateAttributeGroup, oa:IndicatorType, and many other dependencies -->
```

A couple of things to notice:
- The specs are free, but you need to register in order to download them.
- The package is huge - 314 XSD files with over 4000 element and types definitions, with lots of cross-references, so it's not super-easy to find things.
- It's differs from version 1.2 mentioned before. E.g. the recipient field is now named "AttentionOfName", I think?
- Version 4.0 is in development, and it won't be backward-compatible with the version above.
- It is "based on OAGIS AddressBaseType" (so it builds on top of yet another standard). We might want to look into this one.
- It contains solution 4 within, but it allows addressLines to be split into buildings, floors and PO box numbers. This could be useful in some cases.
- It also defines _many_ other elements. All of them are optional, but I'm also quite sure we won't ever use most of them. For example, the `<oa:Preference>` element allows servers to specify which on which days and hours the package should be delivered.
- Documentation is quite exhaustive, but I think we can't expect all developers to read it through. However, it might be enough to provide some examples of how to use this in EWP (so at least a single person will need to understand this all, probably me...).
- In order for Schema validators to work with these, we would need to import these XSDs (or their subsets) into our own repositories, and projects.

**Comment by wrygiel** [comment]
XML example for solution 3 (in its new version, not the obsolete 1.2 one):

``` xml
<hr:Address
    xmlns:hr="http://www.hr-xml.org/3"
    xmlns:oa="http://www.openapplications.org/oagis/9"
>
    <oa:AttentionOfName>Janina Mincer-Daszkiewicz</oa:AttentionOfName>
    <oa:AddressLine>Faculty of Mathematics, Informatics and Mechanics</oa:AddressLine>
    <oa:AddressLine>Banacha 2</oa:AddressLine>
    <oa:CityName>Warszawa</oa:CityName>
    <hr:CountryCode>PL</hr:CountryCode>
    <oa:PostalCode>02-097</oa:PostalCode>
</hr:Address>
```

**Comment by wrygiel** [comment]
### Solution 4+

Since most of you voted for solution 4, I have prepared a specification based on this one. I have also taken some parts out of OAGIS standard mentioned above. This way:
- we make use of "the best practices",
- we are not adding a dependency on a huge external schema.

You can read the specification here:

https://github.com/erasmus-without-paper/ewp-specs-types-address/
