### ISSUE TITLE
Do we need identifiers for academic years?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#14]
In Warsaw we have concluded that we probably don't need IDs for academic **terms**. But what about academic **years**?

I was unable to understand all the arguments clearly. If I remember correctly, it had something to do with the fact that every IIA condition "repeats" on every academic year during which this IIA "lasts". This would mean that every IIA would need to contain a _list_ of academic years (as opposed to start dates and end dates only?), and this might require us to introduce IDs in a predefined format such as `yyyy/yyyy` (e.g. `2015/2016`).

Could someone expand on this? @erasmus-without-paper/all-members

**Comment by mikesteez** [comment]
I don't know, but do we have to process academic years in the system, or is it something that a human will look at to determine what actions has to be performed?

**Comment by wrygiel** [comment]
I'm not sure. As far as I understood this discussion, there's only one use case for these IDs: Comparing IIAs hosted by different partners.

**Comment by kaiqu** [comment]
That's how I understand it too. But since the concept of the academic year permeates the whole project ("everything" seems to be defined in terms of it), It seems important to make sure the partners map remote definitions to the (most) correct local definitions? This suggests a common definition with IDs in a predefined format (typically yyyy/yyyy), start/end dates and maybe a list of terms? Also - although maybe Europe is fairly homogenous in this area(?) this situation might change in the future...

**Comment by georgschermann** [comment]
Having a uniform format for academic years (eg. yyyy/yyyy) would be beneficial i think.

**Comment by kaiqu** [comment]
> Having a uniform format for academic years (eg. yyyy/yyyy) would be beneficial i think.

For academic years defined as "YYYY Fall / YYYY+1 Spring", I agree.
If there are other kinds of academic year, we would need other formats too.

**Comment by georgschermann** [comment]
all academic years covered in our database use yyyy/yyyy or similar formats
these usually consist of 2-5 terms
these terms/trimester/quarters are always distributed onto two calendar years
the academic years usually start with the fall/winter term

so I think yyyy/yyyy should be safe to use

**Comment by kaiqu** [comment]
> all academic years covered in our database use yyyy/yyyy or similar formats

By "your database", do you mean your own SIS or is this definition used by all European partners?

**Comment by wrygiel** [comment]
From wikipedia:

> In most countries, the academic year begins in late summer or early autumn and ends during the following spring or summer. In Northern Hemisphere countries, this means that the academic year lasts from August, September, or October to May, June, or July. In Southern Hemisphere countries, the academic year aligns with the calendar year, lasting from February or March to November or December. The summer may or may not be part of the term system

This would mean that `yyyy/yyyy` should work for Europe, but not for the world.

**Comment by georgschermann** [comment]
"our database" is the database of 100+ HEIs software for student exchange,
never meant that this is worldwide, but will work for europe/erasmus

**Comment by kaiqu** [comment]
Then I suggest we standardize on yyyy/yyyy for now, with the possibility for extensions later.

**Comment by wrygiel** [comment]
I agree, `yyyy/yyyy` should work for us.

**Comment by StefanJahnke** [comment]
agree

**Comment by wrygiel** [comment]
[schema link](https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/blob/v0.1.0/schema.xsd#L27)
