### ISSUE TITLE
CNR specification question

### ISSUE THREAD

**Issue by MartaJuzepczuk** [erasmus-without-paper/ewp-specs-architecture#25]
We have encountered a problem in the specification when we were testing our Outgoing Mobility CNR APIs with Ghent. How exactly should this sentence be understood?

> Servers MUST return a valid (HTTP 200) XML response whenever the request has been properly received

Our understanding is that the API should respond with HTTP 200 regardless of the omobility_ids included in the request. However, Ghent has understood this sentence differently:

> We interpreted 'properly received' as 'validated that the mobility can be processed'.

Can you please clarify this in the specification?

@BavoNootaert

**Comment by wrygiel** [comment]
> Our understanding is that the API should respond with HTTP 200 regardless of the omobility_ids included in the request.

You understood it correctly. That is, this is what I meant when I have written "properly received".

But I can see how this can be misunderstood. The current version of the [CNR introduction](https://github.com/erasmus-without-paper/ewp-specs-architecture#cnr) doesn't explicitly tell you that. I'll try to make it better.

**Comment by wrygiel** [comment]
All the instances of the "properly received" term are now linked to [this new section](https://github.com/erasmus-without-paper/ewp-specs-architecture#bad-cnr-request) of the CNR introduction. I hope it's clear now!

**Comment by huntering** [comment]
Why should we return properly received if we cannot process the request?  Why should the receiving institution not be allowed to do some validation?

**Comment by wrygiel** [comment]
Because "properly received" and "properly processed" are different things. This API was designed to return HTTP 200 whenever the request was "properly received". Please see the section linked above, I tried to describe this as well as I could.

**Comment by huntering** [comment]
I understand that there is a difference between properly received and properly processed, but doing validation by doing a GET is not equal to processing, it's part of the validation process.

**Comment by wrygiel** [comment]
It's just how we intended this to work when we have designed this. CNRs are supposed to be a very simple thing, and such validation should not occur during the CNR processing.

We're also sorry that we haven't specified this properly in the first place, and you have to reimplement this. The purpose of specification is to remove all such ambiguities. However, now this distinction is quite explicit.

**Comment by huntering** [comment]
I don't think that we will reimplement this. It just doesn't make sense. If we receive information that's not valid, it would require us to contact the sending institution via e-mail to notify them, while now they just get a 500 and they are notified right away.
