### ISSUE TITLE
Should we allow self-signed *client* certificates in production environment?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#3]
In https://github.com/erasmus-without-paper/ewp-specs-api-echo/issues/2 @andydowling-ie wrote:

> Geir made the point that self-signed certs should not be used in production in his email earlier today. I'd tend to agree. Although technically self-signed certs could be used if their fingerprints are explicitly trusted by the Registry (i.e. akin to importing a new root CA in your browser), each of these certs needs to be explicitly vetted before being added to the registry. At least if certs are issued by valid CAs, some of this work has been done, and it makes it easier to scale.

@wrygiel:

> I agree that _in general_ self-signed certificates should not be used on production systems. The registry should monitor the manifest files and enforce some policies. However, I suspect, that we might still want to grant partner a (temporary) permission to use a self-signed certificate in some special circumstances. Do you see any security concerns in using self-signed certs in production **if** each such certificate will be reviewed by a human?

@andydowling-ie:

> Self-signed certs are fine by me if reviewed by a human. However, it's just an issue of scale. With a CA-signed cert, the identity of the Subject is checked and we get to piggyback on that process. With self-signed certs, the Registry maintainers would need to take the hit. For incidental usage (i.e. small number of developers/testers/temporary users), it should be fine.

@wrygiel:

> > With self-signed certs, the Registry maintainers would need to take the hit.
> 
> Since we are talking about _client certificates_ only, I see no way avoiding such hit. Without the help of the Registry, how could the server know if the request is coming from within the EWP Network? What I mean is that they'll need the registry even if we're _not_ using self-signed certs.
> 
> I think we can only attempt to reduce this hit (hence the requirement of caching on the client side). Serving DNS Common Names (instead of whole certificates) also seems a good way of reducing the registry load (and has some other benefits).

**Comment by wrygiel** [comment]
@richared wrote:

> Self-signed certificates cannot be allowed in production. This has to be explicitly said in the documentation.

**Comment by JjfBcn** [comment]
Has someone used letsencrypt.org? Could it be an option to avoid the use of self-signed certificates? I read a few months ago about this opensource project, but I'm not sure if it could fit in this project...

**Comment by wrygiel** [comment]
I think most of you missed one important detail: In the 1.0.0 version of the docs, we are considering self-signed **client** certificates **only**. All server certificates MUST be signed by a trusted CA.

**Comment by wrygiel** [comment]
Please note, there is only a `<client-certificates-in-use>` section in the Manifest file. There's not a word on server certificates there. Since all API endpoints will be served over HTTPS (and trusted certificates bound to known domains), there seems to be no need to include server certificates in the manifest.

**Comment by wrygiel** [comment]
Let's sum up all the options:

### Option 1 (the current one)

This is the way it was proposed in the `1.0.0` architecture document:

|  | DEV | PROD |
| --- | :-: | :-: |
| Server certificates | CA-signed only | CA-signed only |
| Client certificates | CA-signed or self-signed | CA-signed or (in special cases) self-signed |

Additional explanation:
- In case of CA-signed server certificates - their CN must match the domain of the URL we are accessing (we get these URLs from the `<apis-implemented>` element of the manifest).
- In case of CA-signed client certificates - their CN must match one of the `client-certificates-in-use/common-name` elements in the manifest.
- In case of self-signed client certificates - they must match one of the `client-certificates-in-use/certificate` elements in the manifest.

The exact definition of "special cases" (when should self-signed client-certificates be allowed in production?) is yet to be decided upon. However, whatever we decide, these rules can be enforced by the registry later on - so this decision does not affect the clients (the clients will just trust to the registry to keep them safe).

### Option 2

Completely disallow self-signed client certificates in production environment. What would be the benefit of this over option 1? This would mean that the `client-certificates-in-use/certificate` elements will be dropped from the manifest.

|  | DEV | PROD |
| --- | :-: | :-: |
| Server certificates | CA-signed only | CA-signed only |
| Client certificates | CA-signed or self-signed | CA-signed only |

### Option 3

Allow self-signed **server** certificates. What would be the benefit of this over option 1? (This would mean that we have to add a `<server-certificates-in-use>` element to the manifest, we currently don't see how this would help with the security or stability.)

|  | DEV | PROD |
| --- | :-: | :-: |
| Server certificates | CA-signed or self-signed | CA-signed or (in special cases) self-signed |
| Client certificates | CA-signed or self-signed | CA-signed or (in special cases) self-signed |

**Comment by wrygiel** [comment]
Discussed this issue in Oslo. The `<common-name>` elements [will be removed](https://github.com/erasmus-without-paper/ewp-specs-architecture/issues/2), but otherwise option 1 seems solid. We will allow the use of self-signed **client** certificates in production.
