### ISSUE TITLE
Decentralized registry?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#4]
There was some discussion about this, so I create the issue to track it in one place.

Victoriano wrote:

> And it really does not have to be centralized, as there are examples of distributed registries, e.g. DNS or blockchain. I'd really recommend considering blockchain for this project as it has some interesting characteristics that would make it very forward looking,

**Comment by mikesteez** [comment]
I think a distributed registry is not needed at this stage of the project. It might never be neccessary.

**Comment by wrygiel** [comment]
I also feel this way, but I would to hear Andy's input on this. @andydowling-ie

**Comment by wrygiel** [comment]
I think we will stick with centralized registry. At least for now.
