### ISSUE TITLE
Consider DANE and DNSSec

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#5]
At the time of creating this issue, I don't know much about the subject. But I'm creating it to track the issue in one place.

Some comments here:
https://github.com/erasmus-without-paper/ewp-specs-architecture/pull/1

**Comment by wrygiel** [comment]
https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities

**Comment by mikesteez** [comment]
I don't think DANE and DNSSec will help this project. The operational aspects of modifying the DNS can be very prohibitive. I believe our NOC will be quite hesitant to add this project to the DNS, and the round trip times for testing can be very long.
