### ISSUE TITLE
Add some error handling rules and a common error response

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#7]
We need to have some rules how common errors should be handled. In particular, clients should be able to recognize between these various situations:
1. They're making an invalid request, so the **client** implementers must fix their code.
2. There's an error on the server side, so it is the **server** implementers that need to be bothered about it.
3. The service is temporarily unavailable (in this case, the client implementers may ask their users to retry in a few minutes).

**Comment by georgschermann** [comment]
I'd suggest standard HTTP Status Codes:
4xx Client Error
5xx Server Error
503 Service Unavailable

**Comment by wrygiel** [comment]
That's exactly what I have suggested too ;) Take a look at the attached pull request.

**Comment by wrygiel** [comment]
There's also a recommended `developer-message` field. We might add more fields later on.
