### ISSUE TITLE
Possible DNS poisoning attacks

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-architecture#9]
This issue has been raised during the workshop in Brussels. It affects the architecture described in the following documents:
- _Architecture and Security_ vesion `1.1.0` (and lower),
- _Discovery Manifest API_ version `2.0.0` (and lower).
## Attack scenario

I'm not 100% sure if I have understood the attack scenario properly, so please comment if something is missing here:
1. The attacker poisons the DNS in such a way, that both **CA** and **EWP Client** resolve the **original server's** domain to the **attacker's** server.
2. The attacker asks the **CA** to issue a certificate for the attacked domain. CA is unable to detect DNS poisoning (?), so the attacker is able to retrieve a valid certificate issued for this domain. (This was a surprise for me!)
3. The attacker serves his own Manifest file on his server. The DNS is still poisoned, and the certificate is valid (signed by CA), so the **EWP Registry** fetches and stores this manifest.
4. The attacker is now able to:
   a) execute requests within the EWP Network (as the attacked EWP Host),
   b) serve malicious responses to other clients in EWP Network.
## Possible solutions

We need to assess the risk of such attack, and propose solutions. (I will update the issue description later on, with a list of such solutions.)
### Solution 1: OV/EV certs

This attack scenario is possible only when Domain Validation (DV) certificates are in use. [Extended Validation (EV) Certificates](https://en.wikipedia.org/wiki/Extended_Validation_Certificate) are DNS-spoofing-proof and Terena provides them for all HEIs **for free**. Organization Validation (OV) certs have similar qualities. For all requests in the EWP Network, the clients will be required to verify if the server uses OV or EV certificate.

**Pros:**
- Very easy to implement (newer OV/EV certs are easy to detect).
- EV certificates are free for all HEIs.
- No need to use a specialized web interface (possibility of automatic updating).
- No need to implement a dedicated web interface.
- Admins do not need to update anything when certificates are renewed (because we do not keep track of server certificates).
- Non-eduGAIN HEIs are supported.
- No need to hardcode Registry's key (nor cert, nor CA) in any clients.

**Cons:**
- If non-educational institutions would like to host things in the network, they would need to purchase an OV/EV certificate (not sure if this is really a "con").
### Solution 2: Web interface with eduGAIN SSO

We can implement a web interface in the Registry Service, which would make use of eduGAIN to authenticate EWP server administrators (SSO). **If** eduGAIN is able to provide us with the proper attributes (we need to be sure that a person is authorized to make such changes) then we can allow the user to paste his server certificates directly into the registry.

**Pros:**
- Some people prefer web interfaces.

**Cons:**
- Unsure if eduGAIN allows to identify admins.
- Admins need to update certificates every time they change.
- Admins need to update more than one certificate (if their APIs are implemented in more than one domain).
- Admins need to use an external web interface. Automatic updating not possible.
- eduGAIN SSO is not well adopted yet (e.g. only 5-7 institutions in Poland provide IdP).
- A decicated web interface would need to be implemented.
- Registry responses would need to additionally signed, clients would need to know the Registry's key/cert in advance.
### Solution 3: Signing manifests with eduGAIN keys

We can require the manifest files to be signed with eduGAIN keys.

**Pros:**
- No need to use a specialized web interface. Possibility of automatic updating.
- No need to implement a dedicated web interface.

**Cons:**
- `<server-credentials>` entry would need to be added to the manifest file.
- Admins need to update certificates every time they change.
- Admins need to update more than one certificate (if their APIs are implemented in more than one domain).
- eduGAIN is not well adopted yet (e.g. only 5-7 institutions in Poland provide IdP).
- Registry responses would need to be additionally signed, clients would need to know the Registry's key/cert in advance.
### Solution 4: Do nothing

We can decide that this kind of attack is **not a valid attack scenario for realistic use today** (as described in detail in [this comment](https://github.com/erasmus-without-paper/ewp-specs-architecture/issues/9#issuecomment-206256728)). The current specification is safe. Clients will still be allowed to trust DV certificates.
### Solition 1B: Require EV for manifest files only

Require EV certificates for hosting Manifest files, but don't require them for hosting any other resources.

These has all the **pros** of **Solution 1**, and some others:
- The Registry Maintainers can still [easily vet](https://github.com/erasmus-without-paper/ewp-specs-architecture/issues/9#issuecomment-206391686) the organization who wants to join the Network (just as in **Solution 1**). They simply need to examine their EV certificate before the new manifest file is imported for the first time.
- If, for some reason, some EWP Hosts have problems getting EV certificates, they still may contact Registry Maintainers and ask for an exception. Since the registry is _the only client_ who will be checking for EV certificates in this solution, it is easy to allow for such exceptions. (But hopefully they won't be required).
- The clients are not required to check for EV certificates. They can make use of the regular CA validation built into common libraries (which is a bit easier).

**Comment by wrygiel** [comment]
@erasmus-without-paper/developers 

I have added three possible solutions. Currently, solution 1 seems to be a clear winner for me.

**Comment by mkurzydlowski** [comment]
I also vote for solution 1.

**Comment by andydowling-ie** [comment]
Solution 1 makes the most sense, in my view.

**Comment by wrygiel** [comment]
@br00k, @mpuzar, Luis, please comment here.

**Comment by mikesteez** [comment]
I think we are mixing things up here. By using eduGAIN we piggyback on the infrastructure for managing the distribution of available hosts in the EWP network (discovery) and their respective certificates. The certificates themselves and how they are issued (self-signe, EV, OV, etc) is on a different (orthogonal) axis.

**Comment by wrygiel** [comment]
As far as I understood, all eduGAIN-based ideas were built on the premise that our current distribution of certificates is somehow unsafe.

Despite many hours of google-searching I could not find ANY proof that this attack scenario is actually possible (I think that CAs are supposed to be ready for such attacks). But some of you were quite sure it was. Some references would be most welcome!

**Comment by andydowling-ie** [comment]
In my experience of building and managing CAs, I can't say I've heard of this type of attack either, but I'm open to learning more. As I see it, EV CAs undertake various out-of-band verification methods prior to issuing certificates (subject to the CAs issuing policy). To my knowledge, an attacker would need to do more than just poison DNS in order to acquire a valid certificate for a domain they claim to own. If the CA relies ONLY on verifying a file at the claimed DNS domain, then yes, DNS poisoning would be an issue. However any decent CA should require appropriate paperwork / telephone / identity verification also.

**Comment by wrygiel** [comment]
> If the CA relies ONLY on verifying a file at the claimed DNS domain, then yes, DNS poisoning would be an issue. 

It seems that services like https://letsencrypt.org/ do exactly that. Getting a DV certificate can now be a completely automated process.

> However any decent CA should require appropriate paperwork / telephone / identity verification also.

These are among the requirements to get an EV certificate.

**Comment by andydowling-ie** [comment]
So shouldn't we just mandate EV certs or those issued with an equivalent verification level?

**Comment by wrygiel** [comment]
That's exactly what we're proposing in Solution 1. But I would like to get the official approval of the people who initially reported the problem first. If I understood it correctly, they have proposed Solution 3 during our meeting in Brussels. (I have thought of Solution 1 later on, and I think it's much better.)

**Comment by wrygiel** [comment]
> By using eduGAIN we piggyback on the infrastructure for managing the distribution of available hosts in the EWP network (discovery) and their respective certificates.

@mikesteez, could you comment on this a little more? Are you describing Solution 3 (as described above), or some other process?

As far as I know, eduGAIN does not store host certificates. The certificates used in the eduGAIN metadata are just containers for keypairs (they are often self-signed and expired), and they cannot (should not?) be directly used for HTTPS transport.

**Comment by vickalaser** [comment]
I will ask my local security expert for a comment on the attack scenario.

**Comment by vickalaser** [comment]
I have received the following response regarding the attack scenario from my colleague Martin Reed.

Yes this is a valid attack scenario, but it is a valid scenario for any system on the Internet, no more with yours, and highly unlikely to succeed. It is unlikely to be successful as:

i) it is now difficult to poison a DNS for many domains as they are starting to use DNSSEC.

ii) it is unlikely that CA will be using the same poisoned DNS (they tend to resolve from the root DNS servers to avoid this kind of “poisoned DNS” and would check the DNSSEC key if it was being used). I did a quick check and confirmed that the .ac.uk is using DNSSEC so that it is possible to verify from that the true nameserver for essex.ac.uk and thus a CA can be sure it is getting the correct essex.ac.uk nameserver. This is true for essex, it is likely to be true for most academic institutions in Europe.

So to cut a long story short, not a valid attack scenario for realistic use today.

There are far likely to be very many more valid attack scenarios in any system that is built in things like faults in application software.

**Comment by wrygiel** [comment]
Thank you!

Updated issue description: Added **Solution 4: Do nothing**.

**Comment by huntering** [comment]
I suppose with doing nothing, you mean that we use SSL and we let every instution choose whether they use DV or EV certificates, right? Then I agree.

**Comment by wrygiel** [comment]
> I suppose with doing nothing, you mean that we use SSL and we let every instution choose whether they use DV or EV certificates, right?

Yes. In **Solution 4** clients wouldn't be required to verify which types of certificates are in place (they would only be required to be signed by CA).

However, if some partners are still not certain about DV security, then I'm okay with **Solution 1** too (OV/EV certs).

**Comment by mikesteez** [comment]
Either way, we need to have a process for adding new members to the network and vetting their certificates and including them into the manifest file.

**Comment by wrygiel** [comment]
That's why **solution 1** might be actually better. We don't need the "vetting" part in this case (CA does that for us).

**Comment by wrygiel** [comment]
We could also require that manifest files are served behind EV certificates, and other resources could remain behind DV certificates (let's call it **solution 1B**). This will help us with the "vetting" and still allow DV certs to be used in other areas. Also, the clients won't need to check for EV certs (only the registry will need to).

**Comment by wrygiel** [comment]
Added a detailed description for **solution 1B** to the issue description.

**Comment by vickalaser** [comment]
I would be interested to see a comment from Brook from  Edugain. Using Edugain might be a long term good political solution even if at present it is not all pervasive. You might at least consider maintaining a regular review of the choice you make against using Edugain. As we discussed in Brussels the solution should closely align with community practice.

**Comment by janinamincer-daszkiewicz** [comment]
I wrote a letter to Brook asking his opinion. What else can we do?
Should we reject good, secure and scalable solution only because community has not yet used it? 
If anybody sees any drawbacks of the proposed solution - other than community practice - let us know about it.

**Comment by wrygiel** [comment]
I believe we will go with **Solution 4 - do nothing**.

Months have passed and none of the people who had originally raised this issue has responded. We will conclude that the issue was raised in error (and the security details of our architecture were not properly understood before reporting the error).

We will encourage the use of EV certificates, at least for hosting manifest files, but we will not require those.
